apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 1q2w3e4r
        - name: MYSQL_DATABASE
          value: production_db
        - name: MYSQL_USER
          value: devHugo
        - name: MYSQL_PASSWORD
          value: 1q2w3e # Cambiado de MYSQL_ROOT_PASSWORD a MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
