apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-rs-vpm
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: myapp
        image: rs-vpm
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE
          value: production_db
        - name: USER
          value: devHugo
        - name: PASS
          value: 1q2w3e
---
apiVersion: v1
kind: Service
metadata:
  name: backend-rs-vpm
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

